/**
 * Journal-shaped manuscript drafts from workspace data.
 * Section order follows CARE / STROBE / SPIRIT-CONSORT / PRISMA educational structure.
 * For Word export via markdown → docx pipeline.
 */
import type { CaseProject } from "./case-report";
import { CARE_ITEMS } from "./case-report";
import type { XsProject } from "./cross-sectional";
import type { CohortProject } from "./cohort";
import type { QuasiProject } from "./quasi";
import type { RctProject } from "./rct";
import { CONSORT_SPIRIT_ITEMS } from "./rct";
import type { Project } from "./types";
import {
  buildMethodsMarkdown,
  buildResultsSkeletonMarkdown,
} from "./manuscript";
import { buildProtocolMarkdown } from "./stages";
import { computeReadiness } from "./readiness";

function v(data: Record<string, unknown> | undefined, key: string): string {
  const x = data?.[key];
  if (x == null) return "";
  const s = String(x).trim();
  return s;
}

function block(title: string, body: string): string[] {
  const text = body.trim() || "—";
  return [`## ${title}`, "", text, ""];
}

function join(...parts: string[][]): string {
  return parts
    .flat()
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

function disclaimer(guide: string): string[] {
  return [
    "---",
    "",
    `*Educational manuscript skeleton generated by EvidenceFlow. Align with target journal instructions and ${guide}. Not a substitute for supervision or journal copy-editing.*`,
    "",
  ];
}

function header(
  title: string,
  kind: string,
  extra?: string
): string[] {
  return [
    `# ${title}`,
    "",
    `> ${kind}`,
    `> Draft date: ${new Date().toISOString().slice(0, 10)}`,
    extra ? `> ${extra}` : "",
    "",
  ].filter(Boolean);
}

/** CARE-ordered case report / series manuscript */
export function buildCaseJournalManuscript(project: CaseProject): string {
  const why = project.stages.why?.data || {};
  const consent = project.stages.consent?.data || {};
  const patient = project.stages.patient?.data || {};
  const timeline = project.stages.timeline?.data || {};
  const assess = project.stages.assessment?.data || {};
  const interv = project.stages.intervention?.data || {};
  const outcome = project.stages.outcome?.data || {};
  const disc = project.stages.discussion?.data || {};
  const rep = project.stages.reporting?.data || {};
  const title = v(rep, "title") || project.title;
  const mode =
    project.mode === "series" || v(why, "modeNote") === "series"
      ? "series"
      : "report";

  const checks = Array.isArray(rep._careChecks)
    ? (rep._careChecks as unknown[]).map(String)
    : [];

  return join(
    header(
      title,
      `Case ${mode} manuscript draft (CARE-inspired structure)`,
      "Verify consent, de-identification, and every clinical fact before submission."
    ),
    v(rep, "keywords")
      ? [`**Keywords:** ${v(rep, "keywords")}`, ""]
      : [],
    block("Title page notes", [
      `Working title: ${title}`,
      `Report type: ${mode === "series" ? "Case series" : "Case report"}`,
      `Objective: ${v(why, "objective") || "—"}`,
    ].join("\n")),
    block("Abstract", v(rep, "abstract")),
    block(
      "Introduction",
      [
        v(why, "whatIsKnown"),
        v(why, "rationale"),
        v(why, "whatThisAdds")
          ? `What this ${mode} adds: ${v(why, "whatThisAdds")}`
          : "",
        v(why, "objective"),
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Patient information",
      [
        v(patient, "baseline"),
        v(patient, "presentation")
          ? `Presentation:\n${v(patient, "presentation")}`
          : "",
        v(patient, "history") ? `History:\n${v(patient, "history")}` : "",
        v(patient, "seriesInclusion")
          ? `Series inclusion:\n${v(patient, "seriesInclusion")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Timeline",
      [v(timeline, "timeline"), v(timeline, "keyDecisionPoints")
        ? `Key decision points:\n${v(timeline, "keyDecisionPoints")}`
        : ""]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Diagnostic assessment",
      [
        v(assess, "findings")
          ? `Findings and investigations:\n${v(assess, "findings")}`
          : "",
        v(assess, "differential")
          ? `Differential diagnosis:\n${v(assess, "differential")}`
          : "",
        v(assess, "finalDx")
          ? `Diagnosis:\n${v(assess, "finalDx")}`
          : "",
        v(assess, "challenges")
          ? `Diagnostic challenges:\n${v(assess, "challenges")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Therapeutic intervention",
      [
        v(interv, "interventions"),
        v(interv, "rationale")
          ? `Rationale:\n${v(interv, "rationale")}`
          : "",
        v(interv, "harms") ? `Adverse effects:\n${v(interv, "harms")}` : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Follow-up and outcomes",
      [
        v(outcome, "outcomes"),
        v(outcome, "followup")
          ? `Follow-up:\n${v(outcome, "followup")}`
          : "",
        v(outcome, "patientPerspective")
          ? `Patient perspective:\n${v(outcome, "patientPerspective")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Discussion",
      [
        v(disc, "literature"),
        v(disc, "limitations")
          ? `Limitations:\n${v(disc, "limitations")}`
          : "",
        v(disc, "takeaways")
          ? `Take-home messages:\n${v(disc, "takeaways")}`
          : "",
        v(disc, "conclusions")
          ? `Conclusions:\n${v(disc, "conclusions")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Patient consent and privacy",
      [
        `Consent status: ${v(consent, "consentStatus") || "—"}`,
        v(consent, "consentNotes"),
        v(consent, "deidentifyPlan")
          ? `De-identification:\n${v(consent, "deidentifyPlan")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    v(rep, "gaps")
      ? block("Gaps before submission", v(rep, "gaps"))
      : [],
    [
      "## CARE-inspired checklist",
      "",
      ...CARE_ITEMS.map(
        (item) =>
          `- [${checks.includes(item.id) ? "x" : " "}] ${item.label}`
      ),
      "",
    ],
    disclaimer("CARE (care-statement.org)")
  );
}

function strobishObservational(opts: {
  title: string;
  kind: string;
  question: Record<string, unknown>;
  design: Record<string, unknown>;
  participants: Record<string, unknown>;
  variables: Record<string, unknown>;
  bias: Record<string, unknown>;
  stats: Record<string, unknown>;
  ethics: Record<string, unknown>;
  reporting: Record<string, unknown>;
  extraSections?: string[][];
}): string {
  const t = v(opts.reporting, "title") || opts.title;
  return join(
    header(t, opts.kind, "STROBE-inspired section order for journal drafting."),
    block("Title and abstract notes", [
      `Title: ${t}`,
      v(opts.reporting, "abstract")
        ? `Abstract draft:\n${v(opts.reporting, "abstract")}`
        : "",
    ]
      .filter(Boolean)
      .join("\n\n")),
    block(
      "Introduction",
      [
        v(opts.question, "topic") || v(opts.question, "background"),
        v(opts.question, "question") || v(opts.question, "objective"),
        v(opts.question, "hypothesis")
          ? `Hypothesis / objective:\n${v(opts.question, "hypothesis")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — study design and setting",
      [
        v(opts.design, "timing") || v(opts.design, "design"),
        v(opts.design, "setting"),
        v(opts.design, "calendar") || v(opts.design, "period"),
        v(opts.design, "cohortType") || v(opts.design, "structure"),
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — participants",
      [
        v(opts.participants, "eligibility") ||
          v(opts.participants, "inclusion"),
        v(opts.participants, "sourcePop") ||
          v(opts.participants, "sampling"),
        v(opts.participants, "sampleSize") ||
          v(opts.participants, "size"),
        v(opts.participants, "timeZero"),
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — variables",
      Object.values(opts.variables)
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n") || "—"
    ),
    block(
      "Methods — bias and confounding",
      Object.values(opts.bias)
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n") || "—"
    ),
    block(
      "Methods — statistical methods",
      Object.values(opts.stats)
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n") || "—"
    ),
    block(
      "Ethics",
      [
        v(opts.ethics, "ethicsStatus") || v(opts.ethics, "status"),
        v(opts.ethics, "consent"),
        v(opts.ethics, "privacy"),
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    ...(opts.extraSections || []),
    block(
      "Discussion scaffold",
      [
        v(opts.reporting, "limitations")
          ? `Limitations:\n${v(opts.reporting, "limitations")}`
          : "Limitations: —",
        v(opts.reporting, "gaps")
          ? `Remaining gaps:\n${v(opts.reporting, "gaps")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    disclaimer("STROBE (strobe-statement.org)")
  );
}

export function buildXsJournalManuscript(project: XsProject): string {
  return strobishObservational({
    title: project.title,
    kind: "Cross-sectional study manuscript draft (STROBE-inspired)",
    question: project.stages.question?.data || {},
    design: project.stages.design?.data || {},
    participants: project.stages.participants?.data || {},
    variables: {
      ...(project.stages.variables?.data || {}),
      ...(project.stages.measurement?.data || {}),
    },
    bias: project.stages.measurement?.data || {},
    stats: project.stages.analysis?.data || {},
    ethics: project.stages.ethics?.data || {},
    reporting: project.stages.reporting?.data || {},
    extraSections: [
      block(
        "Results scaffold",
        "Paste: participant flow, descriptive tables, main associations with uncertainty (CI). Avoid causal language."
      ),
    ],
  });
}

export function buildCohortJournalManuscript(project: CohortProject): string {
  const q = project.stages.question?.data || {};
  const design = project.stages.design?.data || {};
  const part = project.stages.participants?.data || {};
  const exp = project.stages.exposure?.data || {};
  const out = project.stages.outcomes?.data || {};
  const fu = project.stages.followup?.data || {};
  const an = project.stages.analysis?.data || {};
  const eth = project.stages.ethics?.data || {};
  const rep = project.stages.reporting?.data || {};

  return strobishObservational({
    title: project.title,
    kind: "Cohort study manuscript draft (STROBE-inspired)",
    question: q,
    design,
    participants: part,
    variables: { ...exp, ...out },
    bias: {
      misclass: exp.misclass,
      ltfu: fu.ltfu,
      confounders: an.confounders,
    },
    stats: an,
    ethics: eth,
    reporting: rep,
    extraSections: [
      block(
        "Methods — follow-up",
        [v(fu, "followupPlan"), v(fu, "censoring"), v(fu, "completeness")]
          .filter(Boolean)
          .join("\n\n")
      ),
      block(
        "Results scaffold",
        "Paste: flow of participants, follow-up completeness, crude and adjusted estimates with CIs, sensitivity analyses."
      ),
    ],
  });
}

export function buildQuasiJournalManuscript(project: QuasiProject): string {
  const stages = project.stages;
  const pick = (id: string) => stages[id as keyof typeof stages]?.data || {};
  const rep = pick("reporting");
  const title = v(rep, "title") || project.title;

  const chunks: string[][] = [
    header(
      title,
      "Quasi-experimental evaluation manuscript draft (TREND-inspired)",
      "State design limits clearly; avoid over-claiming causality."
    ),
  ];

  const order: { id: string; label: string }[] = [
    { id: "question", label: "Introduction and objectives" },
    { id: "design", label: "Methods — design" },
    { id: "intervention", label: "Methods — intervention / programme" },
    { id: "comparison", label: "Methods — comparison strategy" },
    { id: "outcomes", label: "Methods — outcomes" },
    { id: "validity", label: "Methods — threats to validity" },
    { id: "analysis", label: "Methods — analysis" },
    { id: "ethics", label: "Ethics" },
    { id: "reporting", label: "Reporting notes and limitations" },
  ];

  for (const { id, label } of order) {
    const data = pick(id);
    const body = Object.entries(data)
      .filter(([k]) => !k.startsWith("_"))
      .map(([, val]) => (val == null ? "" : String(val).trim()))
      .filter(Boolean)
      .join("\n\n");
    chunks.push(block(label, body));
  }
  chunks.push(
    block(
      "Results scaffold",
      "Paste: pre/post or interrupted series figures, DiD estimates, parallel trends discussion, sensitivity checks."
    )
  );
  chunks.push(disclaimer("TREND / relevant evaluation reporting guidance"));
  return join(...chunks);
}

/** SPIRIT-leaning protocol + CONSORT-ready results placeholders */
export function buildRctJournalManuscript(project: RctProject): string {
  const g = (id: string) => project.stages[id as keyof typeof project.stages]?.data || {};
  const rep = g("reporting");
  const title = v(rep, "title") || project.title;
  const checks = Array.isArray(rep._consortChecks)
    ? (rep._consortChecks as unknown[]).map(String)
    : [];

  return join(
    header(
      title,
      "Randomised trial protocol / manuscript scaffold (SPIRIT–CONSORT inspired)",
      "Use SPIRIT for protocol registration; CONSORT for the final report."
    ),
    block("Title page", [
      `Title: ${title}`,
      v(rep, "registry") ? `Registration: ${v(rep, "registry")}` : "",
      v(rep, "abstract") ? `Abstract:\n${v(rep, "abstract")}` : "",
    ]
      .filter(Boolean)
      .join("\n\n")),
    block(
      "Background and objectives",
      Object.values(g("question"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — trial design",
      Object.values(g("design"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — participants",
      Object.values(g("participants"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — interventions",
      Object.values(g("intervention"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — randomisation and blinding",
      Object.values(g("randomisation"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — outcomes",
      Object.values(g("outcomes"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Methods — statistics and sample size",
      Object.values(g("statistics"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Ethics and oversight",
      Object.values(g("ethics"))
        .map((x) => (x == null ? "" : String(x).trim()))
        .filter(Boolean)
        .join("\n\n")
    ),
    block(
      "Results scaffold (CONSORT)",
      "Paste: CONSORT flow numbers, baseline table, primary outcome with CI, harms, any interim analyses."
    ),
    block(
      "Discussion scaffold",
      v(rep, "limitations") ||
        "Limitations, generalisability, and comparison with prior trials — write after results are locked."
    ),
    [
      "## SPIRIT/CONSORT-inspired checklist",
      "",
      ...CONSORT_SPIRIT_ITEMS.map(
        (item) =>
          `- [${checks.includes(item.id) ? "x" : " "}] ${item.label}`
      ),
      "",
    ],
    disclaimer("SPIRIT / CONSORT (consort-spirit.org)")
  );
}

/** SR/MA journal package: protocol + methods + results skeleton */
export function buildSrJournalManuscript(project: Project): string {
  const readiness = computeReadiness(project);
  const q = project.stages.question?.data || {};
  const title =
    v(q, "reviewQuestion") || v(q, "topic") || project.title;

  return join(
    header(
      title,
      "Systematic review / meta-analysis manuscript package (PRISMA-inspired)",
      `Workspace readiness ~${readiness.score}%. Educational draft only.`
    ),
    block(
      "Title and review question",
      [
        `Project: ${project.title}`,
        v(q, "reviewQuestion") || v(q, "topic"),
        `PICO — P: ${v(q, "population")}; I: ${v(q, "intervention")}; C: ${v(q, "comparator")}; O: ${v(q, "outcomes")}`,
      ]
        .filter(Boolean)
        .join("\n\n")
    ),
    [
      "## Protocol draft",
      "",
      buildProtocolMarkdown(project)
        .replace(/^#.*\n/, "")
        .trim(),
      "",
    ],
    [
      "## Methods draft",
      "",
      buildMethodsMarkdown(project)
        .replace(/^#.*\n/, "")
        .trim(),
      "",
    ],
    [
      "## Results skeleton",
      "",
      buildResultsSkeletonMarkdown(project)
        .replace(/^#.*\n/, "")
        .trim(),
      "",
    ],
    block(
      "Discussion scaffold",
      "Summarise main findings, certainty (GRADE), limitations of the evidence and of the review process, implications for practice/research. Avoid spin."
    ),
    disclaimer("PRISMA 2020 / Cochrane Handbook as applicable")
  );
}
