import type { Project } from "./types";
import { parseStudies, studiesToMarkdownTable } from "./studies";
import { computeReadiness } from "./readiness";

/** Draft Methods section for a systematic review manuscript */
export function buildMethodsMarkdown(project: Project): string {
  const q = project.stages.question.data;
  const e = project.stages.eligibility.data;
  const p = project.stages.protocol.data;
  const s = project.stages.search.data;
  const sc = project.stages.screening.data;
  const x = project.stages.extraction.data;
  const r = project.stages.rob.data;
  const sy = project.stages.synthesis.data;
  const m = project.stages.metaanalysis.data;
  const g = project.stages.grade.data;

  return [
    `# Methods draft — ${project.title}`,
    ``,
    `> Auto-generated by EvidenceFlow from your workspace. Edit for journal style and completeness. Educational aid only.`,
    ``,
    `## Protocol and registration`,
    ``,
    String(p.objectives || "Objectives: _to be completed_"),
    ``,
    `This review was conducted according to a pre-specified protocol. Registration status: **${p.prosperoId || "not recorded"}**.`,
    ``,
    `## Eligibility criteria`,
    ``,
    `### Inclusion`,
    ``,
    String(e.inclusion || "—"),
    ``,
    `### Exclusion`,
    ``,
    String(e.exclusion || "—"),
    ``,
    `- Language limits: ${e.languages || "—"}`,
    `- Date limits: ${e.dateLimits || "—"}`,
    `- Publication status: ${e.publicationStatus || "—"}`,
    ``,
    `## Information sources and search`,
    ``,
    `We searched the following sources: ${s.databases || "—"}.`,
    ``,
    `### Concept structure`,
    ``,
    String(s.conceptBlocks || "—"),
    ``,
    `### Example search string`,
    ``,
    "```",
    String(s.sampleString || "—"),
    "```",
    ``,
    `Search peer review: ${s.peerReview || "—"}.`,
    ``,
    `## Study selection`,
    ``,
    String(
      sc.processNotes ||
        "Two reviewers independently screened titles/abstracts and full texts; disagreements were resolved by discussion or a third reviewer."
    ),
    ``,
    `Reviewers: ${sc.reviewer1 || "R1"} and ${sc.reviewer2 || "R2"}.`,
    ``,
    `## Data extraction`,
    ``,
    String(
      x.dualExtraction ||
        "Data were extracted using a piloted form. Critical outcome data were dual-extracted."
    ),
    ``,
    `Extraction fields: ${x.formFields || "—"}.`,
    ``,
    `## Risk of bias`,
    ``,
    `Risk of bias was assessed using **${r.tool || "RoB 2 (planned)"}**. ${r.process || ""}`,
    ``,
    String(r.summary || ""),
    ``,
    `## Synthesis`,
    ``,
    `Primary synthesis approach: **${sy.approach || "—"}**.`,
    ``,
    String(sy.comparability || ""),
    ``,
    String(sy.narrativeStructure || ""),
    ``,
    `## Meta-analysis (if applicable)`,
    ``,
    `- Effect measure: ${m.effectMeasure || "—"}`,
    `- Model: ${m.model || "—"}`,
    `- Software: ${m.softwareUsed || "—"}`,
    ``,
    String(m.results || ""),
    ``,
    String(m.heterogeneityNotes || ""),
    ``,
    String(m.sensitivity || ""),
    ``,
    `## Certainty of evidence`,
    ``,
    `We assessed certainty of evidence using GRADE for: ${g.outcomesGraded || "—"}.`,
    ``,
    String(g.certaintyRatings || ""),
    ``,
    `## Review question (PICO)`,
    ``,
    String(q.reviewQuestion || q.topic || "—"),
    ``,
  ].join("\n");
}

export function buildResultsSkeletonMarkdown(project: Project): string {
  const sc = project.stages.screening.data;
  const studies = parseStudies(project.stages.extraction.data._studies);
  const m = project.stages.metaanalysis.data;
  const g = project.stages.grade.data;
  const rep = project.stages.reporting.data;
  const { score } = computeReadiness(project);

  return [
    `# Results skeleton — ${project.title}`,
    ``,
    `> Workspace readiness ~${score}%. Fill gaps before submission.`,
    ``,
    `## Study selection`,
    ``,
    `We identified ${sc.identified ?? "X"} records. After removing ${sc.duplicates ?? "X"} duplicates, ${sc.titleAbstractScreened ?? "X"} records were screened at title/abstract. ${sc.fullTextAssessed ?? "X"} full texts were assessed; ${sc.included ?? "X"} studies met inclusion criteria.`,
    ``,
    `### Full-text exclusions`,
    ``,
    String(sc.exclusionReasons || "—"),
    ``,
    `## Study characteristics`,
    ``,
    studiesToMarkdownTable(studies),
    ``,
    `## Risk of bias`,
    ``,
    String(project.stages.rob.data.summary || "_Summarize domain findings._"),
    ``,
    `## Synthesis of results`,
    ``,
    String(m.results || "_Paste pooled estimates / narrative findings._"),
    ``,
    String(m.heterogeneityNotes || ""),
    ``,
    `## Certainty of evidence`,
    ``,
    String(g.certaintyRatings || g.sofDraft || "—"),
    ``,
    `## Discussion points (from workspace)`,
    ``,
    `### Limitations`,
    ``,
    String(rep.limitations || "—"),
    ``,
    `### Conclusions draft`,
    ``,
    String(rep.conclusions || "—"),
    ``,
  ].join("\n");
}
